---
jobs:
  terraform_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v2
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Use gcloud CLI
        run: gcloud info
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.3
      - name: Run terraform unittest
        run: |
          cd deploy
          terraform init -backend-config=dev.gcs.tfbackend
          terraform workspace select unit-test || terraform workspace new unit-test
          terraform plan -out=plan.out
          terraform show -json plan.out > plan.json
          cd ../test/unit_tests
          python -m unittest check_terraform_plan.py
      - name: Clean up
        if: always()
        run: |
          cd deploy
          terraform init -backend-config=dev.gcs.tfbackend
          terraform workspace select default
          terraform workspace delete -force unit-test
  python_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v2
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Use gcloud CLI
        run: gcloud info
      - name: Run python unittest
        run: |
          pip install -r requirements.txt
          python -m unittest discover -s orchestrator_func/test
          python -m unittest discover -s executor_func/test
  write_docs:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v2
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2
      - name: Generate docs
        run: |
          cd docs
          python infrastructure.py
name: FASS CI CD
"on": [push]
